Reset
cmi-girls-who-code/orpheum-game pull request #59
Opened 2017-04-17 23:04 UTC by yicyao

+ fixed backtomenubutton, redid instruction overlay

2017-04-17 23:25 UTC, clayreimann requested changes
This mostly looks good. I have a few questions though.

2017-04-17 23:25 UTC, clayreimann commented on PhysicsOverlayInstructions.swift
> +class SnowballGamePhysics: SKShapeNode {
Let's make the name of this class a bit more informative. Something that let's us know it explains the physics behind the game.

2017-04-17 23:25 UTC, clayreimann commented on oprheum-game/BaseScene.swift
> +    var instructionOverlay1: InstructionOverlayNode!
I think you can come up with a better name than this. 😉

2017-04-17 23:25 UTC, clayreimann commented on oprheum-game/InstructionOverlayNode.swift
> +//        self.addChild(background)
This will effect all overlays, including the instructions at the beginning of the game. Are you sure this is what you want to do?

2017-04-17 23:25 UTC, clayreimann commented on oprheum-game/SnowballScene.swift
> -        gameObjects.runAction(hideWinSceneAction)
Is there a reason these lines go first now?

2017-04-17 23:25 UTC, clayreimann commented on oprheum-game/SnowballScene.swift
> -        gameObjects.runAction(showWinSceneAction)
Same question.

2017-04-17 23:25 UTC, clayreimann commented on oprheum-game/SnowballScene.swift
> -        start = nil
Same question. Plus why do we no longer set `start = nil`?

2017-04-17 23:25 UTC, clayreimann commented on oprheum-game/SnowballScene.swift
> +//        gameObjects.runAction(showSceneAction)
Is this change intentional?

2017-04-18 03:12 UTC, yicyao commented on oprheum-game/SnowballScene.swift
> -        gameObjects.runAction(hideWinSceneAction)
It was part of the merge (of what I had + master)... does the order matter/where should it go?

2017-04-19 04:01 UTC, clayreimann commented on oprheum-game/SnowballScene.swift
> -        gameObjects.runAction(hideWinSceneAction)
Probably, it looks like it will affect the order in which the `SKAction`s run.

2017-04-24 22:08 UTC, clayreimann approved these changes

2017-04-24 22:08 UTC, merged